language: python
os:
    - linux
    #- osx
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
install:
    - ./ci/travis/${TRAVIS_OS_NAME}.sh
script:
    - tox
cache:
    directories:
        - $HOME/.cache/pip
        - /tmp/vim
