language: python
sudo: false
matrix:
    include:
        # Linux environments
        - python: 2.6
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35

        # OS X environments
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py26
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py27
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py33
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py34
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py35
install:
    - source ci/travis/${TRAVIS_OS_NAME}.sh
script:
    - tox
cache:
    directories:
        - $HOME/.cache/pip
        - /tmp/vim
