version: "{build}"
environment:
    matrix:
        - python: 27
          arch: 32
        - python: 27
          arch: 64
        - python: 35
          arch: 32
        - python: 35
          arch: 64
install:
    - ci\appveyor\install.bat
build_script:
    - tox
cache:
    - '%LOCALAPPDATA%\pip'
    - '%USERPROFILE%\vim'
